/**
 * Deterministic media manifest.
 *
 * Maps a local /assets/ path to the Media Library object WordPress actually
 * returned for it. The content hash is what makes the sync idempotent: an
 * unchanged asset is never re-uploaded, and a changed one always is.
 *
 * The manifest holds no secrets and is committed. Every URL in it came back
 * from WordPress — none is ever constructed, guessed, or pattern-matched from
 * another entry, because nothing downstream can tell a guessed CDN URL from a
 * real one until it renders as a broken image on a live page.
 */

import { createHash } from "node:crypto";

export interface MediaEntry {
  readonly sha256: string;
  readonly mediaId: number;
  readonly url: string;
  readonly width: number;
  readonly height: number;
  readonly bytes: number;
  readonly uploadedAt: string;
}

export interface MediaManifest {
  readonly assets: Record<string, MediaEntry>;
}

export const EMPTY_MANIFEST: MediaManifest = { assets: {} };

export function sha256(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

/**
 * Parse a manifest file, tolerating the earlier shape where a value was a bare
 * URL string. Those are treated as *unverified* and dropped rather than
 * upgraded: a string carries no hash and no media ID, so there is no way to
 * know whether it is current or even real.
 */
export function parseManifest(raw: string): { manifest: MediaManifest; discarded: string[] } {
  const parsed = JSON.parse(raw) as { assets?: Record<string, unknown> };
  const assets: Record<string, MediaEntry> = {};
  const discarded: string[] = [];

  for (const [path, value] of Object.entries(parsed.assets ?? {})) {
    if (typeof value !== "object" || value === null) {
      discarded.push(path);
      continue;
    }
    const entry = value as Partial<MediaEntry>;
    if (
      typeof entry.sha256 !== "string" ||
      typeof entry.mediaId !== "number" ||
      typeof entry.url !== "string"
    ) {
      discarded.push(path);
      continue;
    }
    assets[path] = {
      sha256: entry.sha256,
      mediaId: entry.mediaId,
      url: entry.url,
      width: entry.width ?? 0,
      height: entry.height ?? 0,
      bytes: entry.bytes ?? 0,
      uploadedAt: entry.uploadedAt ?? "",
    };
  }

  return { manifest: { assets }, discarded };
}

export function serializeManifest(manifest: MediaManifest): string {
  const sorted = Object.keys(manifest.assets).sort();
  const assets: Record<string, MediaEntry> = {};
  for (const key of sorted) {
    const entry = manifest.assets[key];
    if (entry) assets[key] = entry;
  }
  return `${JSON.stringify({ _comment: MANIFEST_COMMENT, assets }, null, 2)}\n`;
}

const MANIFEST_COMMENT = [
  "Generated by site/deploy-wordpress.mjs. Do not hand-edit.",
  "Every url and mediaId here was returned by the WordPress Media API.",
  "sha256 is of the local file; a mismatch means the asset changed and must re-upload.",
  "Contains no secrets.",
];

export type SyncAction = "upload" | "reuse" | "replace";

export interface SyncDecision {
  readonly path: string;
  readonly action: SyncAction;
  readonly sha256: string;
  readonly reason: string;
  readonly existing?: MediaEntry;
}

/**
 * Decide, per asset, what the sync must do. Pure — takes hashes, not a
 * filesystem — so the dry run and the real run share one decision function and
 * cannot diverge.
 */
export function planSync(
  manifest: MediaManifest,
  local: readonly { path: string; sha256: string }[],
): readonly SyncDecision[] {
  return local.map(({ path, sha256: hash }) => {
    const existing = manifest.assets[path];
    if (!existing) {
      return { path, action: "upload" as const, sha256: hash, reason: "not in manifest" };
    }
    if (existing.sha256 !== hash) {
      return {
        path, action: "replace" as const, sha256: hash, existing,
        reason: `content changed (${existing.sha256.slice(0, 12)} -> ${hash.slice(0, 12)})`,
      };
    }
    return { path, action: "reuse" as const, sha256: hash, existing, reason: "unchanged" };
  });
}

/** Assets a page references that the manifest cannot resolve to a real URL. */
export function unresolved(
  manifest: MediaManifest,
  referenced: readonly string[],
): readonly string[] {
  return referenced.filter((path) => !manifest.assets[path]?.url);
}

/**
 * Rewrite local /assets/ references to Media Library URLs.
 *
 * Only src and srcset are rewritten. Scanning raw text would also match the
 * .svg source paths named in authoring comments, which are deliberately never
 * uploaded.
 */
export function rewriteAssetUrls(
  markup: string,
  manifest: MediaManifest,
): { markup: string; unmapped: readonly string[] } {
  const unmapped = new Set<string>();

  const rewritten = markup.replace(
    /(\s(?:src|srcset)=")(\/assets\/[A-Za-z0-9._-]+)(")/g,
    (whole, before: string, path: string, after: string) => {
      if (path.endsWith(".svg")) {
        throw new Error(
          `${path} is referenced as an image source, but WordPress rejects ` +
          "image/svg+xml uploads. Reference the rasterised .webp instead.",
        );
      }
      const url = manifest.assets[path]?.url;
      if (!url) {
        unmapped.add(path);
        return whole;
      }
      return before + url + after;
    },
  );

  return { markup: rewritten, unmapped: [...unmapped] };
}
