import Image from "next/image";
import manifest from "../content/art-manifest.json";
import styles from "./BrandImage.module.css";

type ArtName = keyof typeof manifest;

/**
 * A piece of the NOVRA image brand, art-directed for the frame it lands in.
 *
 * Two renders, not one scaled: `public/art/<name>.webp` is composed for the
 * desktop frame and `<name>-narrow.webp` is composed again for the phone, with
 * the subject recentred and closer rather than shrunk. They are swapped by CSS
 * at 620px, so each viewport downloads the one it shows.
 *
 * These are raster because the reference board is photographic in feel. The
 * scenes are generated by frontend/scripts/build-art.mjs and committed; nothing
 * here is fetched at runtime.
 */
export function BrandImage({
  name,
  alt,
  priority = false,
  sizes = "100vw",
  className = "",
}: {
  name: string;
  alt: string;
  priority?: boolean;
  sizes?: string;
  className?: string;
}) {
  const wide = manifest[name as ArtName];
  const narrow = manifest[`${name}-narrow` as ArtName];
  if (!wide || !narrow) return null;

  return (
    <div className={`${styles.art} ${className}`}>
      <Image
        className={styles.wide}
        src={`/art/${name}.webp`}
        alt={alt}
        width={wide.width}
        height={wide.height}
        priority={priority}
        sizes={sizes}
      />
      <Image
        className={styles.narrow}
        src={`/art/${name}-narrow.webp`}
        alt={alt}
        width={narrow.width}
        height={narrow.height}
        priority={priority}
        sizes="100vw"
      />
    </div>
  );
}

/** Whether an article has editorial artwork generated for it. */
export function hasArticleArt(slug: string): boolean {
  return `article-${slug}` in manifest && `article-${slug}-narrow` in manifest;
}
