import { getImageProps } from "next/image";
import manifest from "../content/art-manifest.json";
import styles from "./BrandImage.module.css";

/** The width at which the desktop composition takes over from the phone one. */
const BREAKPOINT = 620;

type ArtName = keyof typeof manifest;

/**
 * A piece of the NOVRA image brand, art-directed for the frame it lands in.
 *
 * Two renders, not one scaled: `public/art/<name>.webp` is composed for the
 * desktop frame and `<name>-narrow.webp` is composed again for the phone, with
 * the subject recentred and closer rather than shrunk.
 *
 * They are chosen by a <picture> element, not by CSS. The previous version
 * rendered both as <img> and hid one with display:none, on the belief that
 * "each viewport downloads the one it shows". That is not how display:none
 * works — it suppresses layout, not loading. Measured in Chromium: at 390px
 * the 2000x1573 desktop composition reported shown=false loaded=true, so every
 * phone was downloading a picture it never displayed, and the same happened in
 * reverse on desktop. A <source media> is the mechanism that actually makes
 * the browser pick one, because the choice happens before the fetch.
 *
 * getImageProps rather than hand-written srcsets: it keeps the optimizer's
 * per-width variants and AVIF negotiation, which is the part of next/image
 * worth keeping once the element itself has to be a <picture>.
 *
 * These are raster because the reference board is photographic in feel. The
 * scenes are generated by frontend/scripts/build-art.mjs and committed;
 * nothing here is fetched at runtime.
 */
export function BrandImage({
  name,
  alt,
  priority = false,
  sizes = "100vw",
  className = "",
}: {
  name: string;
  alt: string;
  priority?: boolean;
  sizes?: string;
  className?: string;
}) {
  const wide = manifest[name as ArtName];
  const narrow = manifest[`${name}-narrow` as ArtName];
  if (!wide || !narrow) return null;

  const shared = {
    alt,
    priority,
    // A priority image is the one the page is waiting on, so it says so.
    // Without this Lighthouse reports the LCP request as un-hinted, and the
    // browser schedules it against everything else in the head.
    fetchPriority: priority ? ("high" as const) : undefined,
  };

  const { props: wideProps } = getImageProps({
    ...shared,
    src: `/art/${name}.webp`,
    width: wide.width,
    height: wide.height,
    sizes,
  });

  const { props: narrowProps } = getImageProps({
    ...shared,
    src: `/art/${name}-narrow.webp`,
    width: narrow.width,
    height: narrow.height,
    sizes: "100vw",
  });

  /*
   * The phone render is the <img> fallback rather than a third <source>: an
   * <img> is what a browser that understands neither media queries nor
   * <picture> will load, and serving it the smaller composition is the better
   * failure. Its intrinsic width/height come from the manifest, so the box is
   * reserved before the bytes arrive and the layout does not shift.
   */
  return (
    <picture className={`${styles.art} ${className}`}>
      <source
        media={`(min-width: ${BREAKPOINT}px)`}
        srcSet={wideProps.srcSet}
        sizes={wideProps.sizes}
        width={wide.width}
        height={wide.height}
      />
      {/* alt is repeated explicitly rather than left to the spread: it is in
          narrowProps, but a reader — and jsx-a11y — should be able to see that
          from the element itself. */}
      <img {...narrowProps} alt={alt} className={styles.image} />
    </picture>
  );
}

/** Whether an article has editorial artwork generated for it. */
export function hasArticleArt(slug: string): boolean {
  return `article-${slug}` in manifest && `article-${slug}-narrow` in manifest;
}
