/**
 * The single data layer. Every page reads content from here and nowhere else.
 *
 * The committed snapshot is canonical. It is generated by
 * frontend/scripts/build-snapshot.mjs from the exact payloads that were
 * published, and it is imported — not read from disk — so that a deployment
 * cannot be assembled without it. The previous arrangement made it an optional
 * runtime file, a deploy left it out to save bytes, and five complete articles
 * were published as five empty ones.
 *
 * Live WordPress is an overlay on top of that, never a replacement for it. It
 * may correct a title, a date or an excerpt freely, and it may replace a body
 * only when the body it returns is demonstrably a whole article. An unparseable
 * body is a fact about WordPress markup, not about the article, and it must
 * never be able to empty one.
 */
import pagesJson from "../../content/pages.json";
import mediaJson from "../../content/media-map.json";
import snapshotJson from "../../content/cms-snapshot.json";
import type { Article, SiteContent } from "./types";
import { fetchArticles } from "./wordpress";
import { inspectBody, readingTime, wordCount } from "./integrity";

const pages = (pagesJson as unknown as { pages: SiteContent["pages"] }).pages;
const mediaMap = mediaJson as Record<string, string>;
const canonical = (snapshotJson as unknown as Pick<SiteContent, "articles">).articles;

export type ContentOrigin = "snapshot" | "snapshot+live";

export interface LoadedContent extends SiteContent {
  origin: ContentOrigin;
  /** Slugs whose body came from the live API rather than the snapshot. */
  liveBodies: string[];
}

let cached: Promise<LoadedContent> | null = null;

/**
 * Fail the build rather than publish a hollow article.
 *
 * This runs on the final merged content, so it judges what a reader will
 * actually be served — not what either source claimed on its own.
 */
function assertComplete(articles: Article[]): void {
  if (articles.length === 0) {
    throw new Error("No article content: the canonical snapshot is empty.");
  }
  const failures = articles.flatMap((article) => {
    const report = inspectBody(article.bodyHtml, {
      excerptWords: wordCount(article.excerpt),
    });
    return report.ok ? [] : [`  ${article.slug}: ${report.reasons.join("; ")}`];
  });
  if (failures.length) {
    throw new Error(
      `Article content integrity failed for ${failures.length} of ${articles.length} articles:\n${failures.join("\n")}`,
    );
  }
}

async function load(): Promise<LoadedContent> {
  const live = await fetchArticles(mediaMap);
  const liveBodies: string[] = [];

  const bySlug = new Map((live ?? []).map((post) => [post.slug, post]));
  const merged: Article[] = canonical.map((known) => {
    const post = bySlug.get(known.slug);
    if (!post) return known;
    bySlug.delete(known.slug);

    /*
     * Metadata merges unconditionally — an edited title or a corrected date is
     * exactly what a CMS is for. The body only merges when it survives the same
     * inspection the build gate applies, measured against the canonical body it
     * would be replacing.
     */
    const report = inspectBody(post.bodyHtml, {
      excerptWords: wordCount(post.excerpt || known.excerpt),
      canonicalWords: wordCount(known.bodyHtml),
      canonicalHeadings: (known.bodyHtml.match(/<h[2-4][\s>]/gi) ?? []).length,
    });
    if (report.ok) liveBodies.push(known.slug);

    return {
      ...known,
      id: post.id,
      title: post.title || known.title,
      excerpt: post.excerpt || known.excerpt,
      permalink: post.permalink || known.permalink,
      date: post.date || known.date,
      modified: post.modified || known.modified,
      bodyHtml: report.ok ? post.bodyHtml : known.bodyHtml,
    };
  });

  /*
   * Anything left in the map was published after the snapshot was taken. It has
   * no canonical body to fall back to, so it is admitted only if its live body
   * stands up on its own — and then it is subject to the same build gate.
   */
  for (const post of bySlug.values()) {
    const report = inspectBody(post.bodyHtml, { excerptWords: wordCount(post.excerpt) });
    if (!report.ok) continue;
    liveBodies.push(post.slug);
    merged.push({
      ...post,
      dateDisplay: new Date(post.date).toLocaleDateString("en-GB", {
        day: "numeric",
        month: "long",
        year: "numeric",
      }),
      dateMachine: post.date.slice(0, 10),
      readingTime: "",
      topic: "Analysis",
      category: "Analysis",
      hero: { src: "", alt: "", width: 0, height: 0 },
      sources: [],
    });
  }

  /*
   * Reading time is derived last, from the body that will be rendered. It is
   * never carried over from the snapshot or from a previous fetch, because a
   * stale reading time beside a changed body is how "1 min read" survived
   * beside a complete article in the first place.
   */
  const articles = merged.map((article) => ({
    ...article,
    readingTime: readingTime(article.bodyHtml),
  }));

  assertComplete(articles);
  articles.sort((a, b) => b.date.localeCompare(a.date));

  return {
    generatedAt: "",
    pages,
    articles,
    origin: liveBodies.length ? "snapshot+live" : "snapshot",
    liveBodies,
  };
}

export function getContent(): Promise<LoadedContent> {
  cached ??= load();
  return cached;
}

export async function getArticles(): Promise<Article[]> {
  return (await getContent()).articles;
}

export async function getArticle(path: string): Promise<Article | undefined> {
  const articles = await getArticles();
  return articles.find((article) => article.path === path);
}

export async function getPages() {
  return pages;
}

export type { Article } from "./types";
