/**
 * The single data layer. Every page reads content from here and nowhere else.
 *
 * Two sources, one shape. The committed snapshot is content taken from the CMS
 * and re-expressed as typed data; the REST client fetches the same content live.
 * Live wins where it is available and comprehensible, the snapshot fills the
 * fields REST does not carry, and the snapshot alone serves when the API cannot
 * be reached — which is the normal case inside the migration sandbox, where
 * egress to public-api.wordpress.com is blocked.
 *
 * There is deliberately no second copy of any article. The snapshot is
 * generated by frontend/scripts/build-snapshot.mjs from the exact payloads that
 * were published to WordPress; editing content here would fork it.
 */
import snapshotJson from "../../content/cms-snapshot.json";
import mediaJson from "../../content/media-map.json";
import type { Article, SiteContent } from "./types";
import { fetchArticles } from "./wordpress";

const snapshot = snapshotJson as unknown as SiteContent;
const mediaMap = mediaJson as Record<string, string>;

export type ContentOrigin = "wordpress-rest" | "snapshot";

export interface LoadedContent extends SiteContent {
  origin: ContentOrigin;
}

let cached: Promise<LoadedContent> | null = null;

async function load(): Promise<LoadedContent> {
  const live = await fetchArticles(mediaMap);
  if (!live || live.length === 0) {
    return { ...snapshot, origin: "snapshot" };
  }

  const bySlug = new Map(snapshot.articles.map((article) => [article.slug, article]));
  const articles: Article[] = live.map((post) => {
    const known = bySlug.get(post.slug);
    if (!known) {
      // A post published after this snapshot was taken. It renders with what
      // REST provides; the fields REST has no concept of get honest defaults
      // rather than borrowed ones.
      return {
        ...post,
        dateDisplay: new Date(post.date).toLocaleDateString("en-GB", {
          day: "numeric",
          month: "long",
          year: "numeric",
        }),
        dateMachine: post.date.slice(0, 10),
        readingTime: `${Math.max(1, Math.round(post.bodyHtml.split(/\s+/).length / 220))} min read`,
        topic: "Analysis",
        category: "Analysis",
        hero: { src: "", alt: "", width: 0, height: 0 },
        sources: [],
      };
    }
    return {
      ...known,
      ...post,
      // An unparseable live body means the CMS markup moved; keep the one that
      // is known to be complete.
      bodyHtml: post.bodyHtml || known.bodyHtml,
    };
  });

  articles.sort((a, b) => b.date.localeCompare(a.date));
  return { ...snapshot, articles, origin: "wordpress-rest" };
}

export function getContent(): Promise<LoadedContent> {
  cached ??= load();
  return cached;
}

export async function getArticles(): Promise<Article[]> {
  return (await getContent()).articles;
}

export async function getArticle(path: string): Promise<Article | undefined> {
  const articles = await getArticles();
  return articles.find((article) => article.path === path);
}

export async function getPages() {
  return (await getContent()).pages;
}

export type { Article } from "./types";
