/**
 * The single data layer. Every page reads content from here and nowhere else.
 *
 * Two sources, one shape. The committed snapshot is content taken from the CMS
 * and re-expressed as typed data; the REST client fetches the same content live.
 * Live wins where it is available and comprehensible, the snapshot fills the
 * fields REST does not carry, and the snapshot alone serves when the API cannot
 * be reached — which is the normal case inside the migration sandbox, where
 * egress to public-api.wordpress.com is blocked.
 *
 * There is deliberately no second copy of any article. The snapshot is
 * generated by frontend/scripts/build-snapshot.mjs from the exact payloads that
 * were published to WordPress; editing content here would fork it.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import pagesJson from "../../content/pages.json";
import mediaJson from "../../content/media-map.json";
import type { Article, SiteContent } from "./types";
import { fetchArticles } from "./wordpress";

const pages = (pagesJson as unknown as { pages: SiteContent["pages"] }).pages;
const mediaMap = mediaJson as Record<string, string>;

/*
 * The offline article fallback, read from disk rather than imported.
 *
 * A deployment built where the CMS is reachable does not need it and can ship
 * without the file; a build in an environment with no egress — the migration
 * sandbox — depends on it entirely. An import would make it mandatory at
 * compile time for both, so it is read at runtime and allowed to be absent.
 */
function readSnapshot(): Pick<SiteContent, "articles"> | null {
  try {
    const path = join(process.cwd(), "content", "cms-snapshot.json");
    return JSON.parse(readFileSync(path, "utf8")) as Pick<SiteContent, "articles">;
  } catch {
    return null;
  }
}

export type ContentOrigin = "wordpress-rest" | "snapshot";

export interface LoadedContent extends SiteContent {
  origin: ContentOrigin;
}

let cached: Promise<LoadedContent> | null = null;

async function load(): Promise<LoadedContent> {
  const snapshot = readSnapshot();
  const live = await fetchArticles(mediaMap);

  if (!live || live.length === 0) {
    if (!snapshot || snapshot.articles.length === 0) {
      // Neither source produced an article. Failing here is deliberate: the
      // alternative is a deploy that looks finished and publishes an empty
      // index and five empty articles.
      throw new Error(
        "No article content: the WordPress REST API was unreachable and content/cms-snapshot.json is missing or empty.",
      );
    }
    return { generatedAt: "", pages, articles: snapshot.articles, origin: "snapshot" };
  }

  const bySlug = new Map((snapshot?.articles ?? []).map((article) => [article.slug, article]));
  const articles: Article[] = live.map((post) => {
    const known = bySlug.get(post.slug);
    if (!known) {
      // A post published after this snapshot was taken. It renders with what
      // REST provides; the fields REST has no concept of get honest defaults
      // rather than borrowed ones.
      return {
        ...post,
        dateDisplay: new Date(post.date).toLocaleDateString("en-GB", {
          day: "numeric",
          month: "long",
          year: "numeric",
        }),
        dateMachine: post.date.slice(0, 10),
        readingTime: `${Math.max(1, Math.round(post.bodyHtml.split(/\s+/).length / 220))} min read`,
        topic: "Analysis",
        category: "Analysis",
        hero: { src: "", alt: "", width: 0, height: 0 },
        sources: [],
      };
    }
    return {
      ...known,
      ...post,
      // An unparseable live body means the CMS markup moved; keep the one that
      // is known to be complete.
      bodyHtml: post.bodyHtml || known.bodyHtml,
    };
  });

  articles.sort((a, b) => b.date.localeCompare(a.date));
  return { generatedAt: "", pages, articles, origin: "wordpress-rest" };
}

export function getContent(): Promise<LoadedContent> {
  cached ??= load();
  return cached;
}

export async function getArticles(): Promise<Article[]> {
  return (await getContent()).articles;
}

export async function getArticle(path: string): Promise<Article | undefined> {
  const articles = await getArticles();
  return articles.find((article) => article.path === path);
}

export async function getPages() {
  return pages;
}

export type { Article } from "./types";
